server:
  port: 80

  tomcat:
    uri-encoding: UTF-8

web:
  front-path: C:\Users\Avalon\Desktop\upload\

spring:
  resources:
    static-locations: file:${web.front-path}

logging:
  config: classpath:logback.xml